name: deploy
on:
  push:
    branches:
      - ci
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm build

      - name: SCP deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          target: /site/dev/spotmap
          source: dist
          rm: true
          strip_components: 1
